@echo off
REM ###########################################################################
REM Script generated by Fortify Scan Wizard (c) 2011-2025 Open Text
REM Created on 2025/07/17 17:26:26
REM ###########################################################################
REM Generated for the following languages:
REM 	C#.NET / VB.NET
REM 	JavaScript / TypeScript
REM 	XML
REM ###########################################################################
REM FPR - the name of analysis results file
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM BUILDID - the SCA build ID
REM ARGFILE - the name of the argument file that's passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java bytecode translation in the SCA
REM MEMORY - the memory settings for SCA
REM SCANSWITCHES - parameters to pass in the SCA analysis phase
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM CLIENT - the name of the fortifyclient executable
REM SSCURL - the SSC url for uploading the FPR
REM SSCAPPLICATION - the name of the application to upload the FPR to
REM SSCVERSION - the name of the application version to upload the FPR to
REM SSCTOKEN - the token for authenticating the FPR upload
REM OLDFILENUMBER - this defines the file that contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="Fortifyrichesdotnet-master.fpr"
set SSCURL=https://solution.ntshanoi.vn:8443/ssc
set SSCAPPLICATION="Nancy"
set SSCVERSION="1.0"
set SSCTOKEN=1401d072-444a-4c97-b0ec-9ce133918b21
set CLIENT=fortifyclient
set BUILDID="richesdotnet-master"
set ARGFILE="Fortifyrichesdotnet-master.bat.args"
set BYTECODE_ARGFILE="Fortifyrichesdotnet-master.bat.bytecode.args"
set MEMORY=-Xmx29490M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set SCANSWITCHES=""
set OLDFILENUMBER="Fortifyrichesdotnet-master.bat.fileno"
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="C:\Users\Administrator\Downloads\richesdotnet-master"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################

set SCANSWITCHES=-Dcom.fortify.sca.Phase0HigherOrder.Languages=javascript,typescript %SCANSWITCHES%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Running Build Integration
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID%  devenv "C:\Users\Administrator\Downloads\richesdotnet-master\RichesDotnet.sln" /REBUILD Debug
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% %SCANSWITCHES% -scan -f %FPR%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Uploading scan to SSC
%CLIENT% -url %SSCURL% -authtoken %SSCTOKEN% uploadFPR -file %FPR% -application %SSCAPPLICATION% -applicationVersion %SSCVERSION%
IF %ERRORLEVEL% NEQ 0  (
echo fortifyclient failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
