@echo off
REM ###########################################################################
REM Script generated by Fortify Scan Wizard (c) 2011-2025 Open Text
REM Created on 2025/07/17 15:50:49
REM ###########################################################################
REM Generated for the following languages:
REM 	C#.NET / VB.NET
REM 	JavaScript / TypeScript
REM 	XML
REM ###########################################################################
REM FPR - the name of analysis results file
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM BUILDID - the SCA build ID
REM ARGFILE - the name of the argument file that's passed to SCA
REM BYTECODE_ARGFILE - the name of the argument file for Java bytecode translation in the SCA
REM MEMORY - the memory settings for SCA
REM SCANSWITCHES - parameters to pass in the SCA analysis phase
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM OLDFILENUMBER - this defines the file that contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="FortifyRichesDotnet.fpr"
set BUILDID="RichesDotnet"
set ARGFILE="FortifyRichesDotnet.bat.args"
set BYTECODE_ARGFILE="FortifyRichesDotnet.bat.bytecode.args"
set MEMORY=-Xmx29490M -Xms400M -Xss24M 
set LAUNCHERSWITCHES=""
set SCANSWITCHES=""
set OLDFILENUMBER="FortifyRichesDotnet.bat.fileno"
set FILENOMAXDIFF=10
set ENABLE_BYTECODE=false

set PROJECTROOT0="C:\Users\Administrator\Downloads\richesdotnet-master\RichesDotnet"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >%ARGFILE%
echo. >%BYTECODE_ARGFILE%
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM BYTECODE_ARGS" %SCAScriptFile%' ) DO (
   set ENABLE_BYTECODE=true
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~18! >> %BYTECODE_ARGFILE%
)
ENDLOCAL && set ENABLE_BYTECODE=%ENABLE_BYTECODE%

REM ###########################################################################

echo Searching .NET Framework Version...
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.7.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.7.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.7.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.7.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7" (
set LAUNCHERSWITCHES=-dotnet-version 4.7 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.7
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.6.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6" (
set LAUNCHERSWITCHES=-dotnet-version 4.6 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.6
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.2 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.2
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1" (
set LAUNCHERSWITCHES=-dotnet-version 4.5.1 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5.1
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" (
set LAUNCHERSWITCHES=-dotnet-version 4.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.5
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0" (
set LAUNCHERSWITCHES=-dotnet-version 4.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 4.0
GOTO DOTNETSELECTED
)
IF EXIST "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5" (
set LAUNCHERSWITCHES=-dotnet-version 3.5 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.5
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 3.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 3.0
GOTO DOTNETSELECTED
)
reg QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727" /v Install 2>NUL >NUL
IF %ERRORLEVEL%==0 (
set LAUNCHERSWITCHES=-dotnet-version 2.0 %LAUNCHERSWITCHES%
echo Found .NET Framework Version 2.0
GOTO DOTNETSELECTED
)
:DOTNETSELECTED
REM ###########################################################################

set SCANSWITCHES=-Dcom.fortify.sca.Phase0HigherOrder.Languages=javascript,typescript %SCANSWITCHES%

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
IF %ENABLE_BYTECODE%==true (
echo Translating Java bytecode files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%BYTECODE_ARGFILE%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% %SCANSWITCHES% -scan -f %FPR%
IF %ERRORLEVEL% NEQ 0  (
echo sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Bin\amd64\Microsoft.VC90.CRT\msvcr90.dll;PROJECTROOT0_MARKER\Bin\amd64\sqlceca40.dll;PROJECTROOT0_MARKER\Bin\amd64\sqlcecompact40.dll;PROJECTROOT0_MARKER\Bin\amd64\sqlceer40EN.dll;PROJECTROOT0_MARKER\Bin\amd64\sqlceme40.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Bin\amd64\sqlceqp40.dll;PROJECTROOT0_MARKER\Bin\amd64\sqlcese40.dll;PROJECTROOT0_MARKER\Bin\System.Data.SqlServerCe.dll;PROJECTROOT0_MARKER\Bin\System.Data.SqlServerCe.Entity\System.Data.SqlServerCe.Entity.dll;PROJECTROOT0_MARKER\Bin\System.Web.Providers.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Bin\x86\Microsoft.VC90.CRT\msvcr90.dll;PROJECTROOT0_MARKER\Bin\x86\sqlceca40.dll;PROJECTROOT0_MARKER\Bin\x86\sqlcecompact40.dll;PROJECTROOT0_MARKER\Bin\x86\sqlceer40EN.dll;PROJECTROOT0_MARKER\Bin\x86\sqlceme40.dll"
REM ARGS "-libdirs"
REM ARGS "PROJECTROOT0_MARKER\Bin\x86\sqlceqp40.dll;PROJECTROOT0_MARKER\Bin\x86\sqlcese40.dll"
REM ARGS "PROJECTROOT0_MARKER"
