name: Fortify AST Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '25 7 * * 6'
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Run Fortify Scan (FoD)
        uses: fortify/github-action@v1
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          # Fortify on Demand configuration
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}  # Hoặc PAT nếu bạn dùng PAT
          
          # Optional settings
          DO_WAIT: true             # Chờ scan hoàn tất trước khi job kết thúc
          DO_POLICY_CHECK: true     # Fail nếu policy check không đạt
          DO_EXPORT: true           # Xuất kết quả sang GitHub Code Scanning dashboard
